name: Update Petition RSS

on:
  schedule:
    - cron: '0 */6 * * *' # S'exécute toutes les 6 heures
  workflow_dispatch:      # Permet de lancer le script manuellement pour tester

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Autorise la publication sur la branche gh-pages
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests feedgen pytz

      - name: Generate RSS
        run: |
          python generate_rss.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages # Le XML sera sur cette branche isolée
